# Generated by Django 5.2.6 on 2025-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tom', models.CharField(blank=True, max_length=12)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
