# Generated by Django 5.2.6 on 2025-09-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='bpm',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='musica',
            name='cifra',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='musica',
            name='tom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
